[package]
name = "htmlupdater"
version = "0.1.0"
edition = "2021"

[dependencies]
eldenring-companion = { path = "../eldenring-companion" }
structopt = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
scraper = "0.19.0"
ego-tree = "0.6.2"