[package]
name = "paramextract"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
byteorder = "1.5.0"
clap = { version = "4.5.11", features = ["derive"] }
libaes = "0.7.0"
memchr = "2.7.4"
zstd = "0.13.2"
